return {
    -- VWE Vehicles

    vwe_550ss = {
        name = '550SS',
        brand = 'Declasse',
        model = 'vwe_550ss',
        price = 100000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_550ss`,
    },
    vwe_adder1 = {
        name = 'Adder',
        brand = 'Truffade',
        model = 'vwe_adder1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_adder1`,
    },
    vwe_admiral1 = {
        name = 'Admiral',
        brand = 'Benefactor',
        model = 'vwe_admiral1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_admiral1`,
    },
    vwe_alamo1 = {
        name = 'Alamo 2500LS',
        brand = 'Declasse',
        model = 'vwe_alamo1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_alamo1`,
    },
    vwe_alamo2 = {
        name = 'Alamo 2500LS',
        brand = 'Declasse',
        model = 'vwe_alamo2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_alamo2`,
    },
    vwe_alamo3 = {
        name = 'Alamo',
        brand = 'Declasse',
        model = 'vwe_alamo3',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_alamo3`,
    },
    vwe_ardent1 = {
        name = 'Ardent',
        brand = 'Ocelot',
        model = 'vwe_ardent1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_ardent1`,
    },
    vwe_argento1 = {
        name = 'Argento',
        brand = 'Obey',
        model = 'vwe_argento1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_argento1`,
        tier = 'S',
    },
    vwe_ariant1 = {
        name = 'Ariant',
        brand = 'Karin',
        model = 'vwe_ariant1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_ariant1`,
    },
    vwe_banshee1 = {
        name = 'Banshee',
        brand = 'Bravado',
        model = 'vwe_banshee1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_banshee1`,
    },
    vwe_bison1 = {
        name = 'Bison',
        brand = 'Bravado',
        model = 'vwe_bison1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_bison1`,
    },
    vwe_bison2 = {
        name = 'Bison',
        brand = 'Bravado',
        model = 'vwe_bison2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_bison2`,
    },
    vwe_blazer1 = {
        name = 'Blazer',
        brand = 'Nagasaki',
        model = 'vwe_blazer1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_blazer1`,
    },
    vwe_bobcat1 = {
        name = 'Bobcat',
        brand = 'Vapid',
        model = 'vwe_bobcat1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_bobcat1`,
    },
    vwe_bobcat2 = {
        name = 'Bobcat',
        brand = 'Vapid',
        model = 'vwe_bobcat2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_bobcat2`,
    },
    vwe_bobcatxl1 = {
        name = 'Bobcat XL',
        brand = 'Vapid',
        model = 'vwe_bobcatxl1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_bobcatxl1`,
    },
    vwe_bobcatxl2 = {
        name = 'Bobcat XL',
        brand = 'Vapid',
        model = 'vwe_bobcatxl2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_bobcatxl2`,
    },
    vwe_bobcatxl3 = {
        name = 'Bobcat XL',
        brand = 'Vapid',
        model = 'vwe_bobcatxl3',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_bobcatxl3`,
    },
    vwe_boxville1 = {
        name = 'Boxville',
        brand = 'Brute',
        model = 'vwe_boxville1',
        price = 45000,
        category = 'vans',
        type = 'automobile',
        hash = `vwe_boxville1`,
    },
    vwe_boxville2 = {
        name = 'Boxville',
        brand = 'Brute',
        model = 'vwe_boxville2',
        price = 45000,
        category = 'vans',
        type = 'automobile',
        hash = `vwe_boxville2`,
    },
    vwe_brigham1 = {
        name = 'Brigham',
        brand = 'Declasse',
        model = 'vwe_brigham1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_brigham1`,
    },
    vwe_buffalo1 = {
        name = 'Buffalo',
        brand = 'Bravado',
        model = 'vwe_buffalo1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_buffalo1`,
    },
    vwe_buffalo2 = {
        name = 'Buffalo',
        brand = 'Bravado',
        model = 'vwe_buffalo2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_buffalo2`,
    },
    vwe_buffalo3 = {
        name = 'Buffalo',
        brand = 'Bravado',
        model = 'vwe_buffalo3',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_buffalo3`,
    },
    vwe_buffalo4 = {
        name = 'Buffalo',
        brand = 'Bravado',
        model = 'vwe_buffalo4',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_buffalo4`,
    },
    vwe_buffalo5 = {
        name = 'Buffalo',
        brand = 'Bravado',
        model = 'vwe_buffalo5',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_buffalo5`,
    },
    vwe_buffalo6 = {
        name = 'Buffalo',
        brand = 'Bravado',
        model = 'vwe_buffalo6',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_buffalo6`,
    },
    vwe_buffalo7 = {
        name = 'Buffalo',
        brand = 'Bravado',
        model = 'vwe_buffalo7',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_buffalo7`,
    },
    vwe_burrito1 = {
        name = 'Burrito',
        brand = 'Declasse',
        model = 'vwe_burrito1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_burrito1`,
    },
    vwe_burrito2 = {
        name = 'Burrito',
        brand = 'Declasse',
        model = 'vwe_burrito2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_burrito2`,
    },
    vwe_bus1 = {
        name = 'Bus',
        brand = 'Brute',
        model = 'vwe_bus1',
        price = 42481,
        category = 'import',
        type = 'automobile',
        hash = `vwe_bus1`,
    },
    vwe_caddy1 = {
        name = 'Caddy',
        brand = 'Nagasaki',
        model = 'vwe_caddy1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_caddy1`,
    },
    vwe_caracara1 = {
        name = 'Caracara',
        brand = 'Vapid',
        model = 'vwe_caracara1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_caracara1`,
    },
    vwe_castella1 = {
        name = 'Castella',
        brand = 'Shitzu',
        model = 'vwe_castella1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_castella1`,
    },
    vwe_cavalcade1 = {
        name = 'Cavalcade',
        brand = 'Albany',
        model = 'vwe_cavalcade1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cavalcade1`,
    },
    vwe_cbus1 = {
        name = 'Charter Bus',
        brand = 'Brute',
        model = 'vwe_cbus1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cbus1`,
    },
    vwe_cerberus1 = {
        name = 'Cerberus',
        brand = 'MTL',
        model = 'vwe_cerberus1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cerberus1`,
    },
    vwe_cerberus2 = {
        name = 'Cerberus',
        brand = 'MTL',
        model = 'vwe_cerberus2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cerberus2`,
    },
    vwe_cerberus3 = {
        name = 'Cerberus',
        brand = 'MTL',
        model = 'vwe_cerberus3',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cerberus3`,
    },
    vwe_cerberus4 = {
        name = 'Cerberus',
        brand = 'MTL',
        model = 'vwe_cerberus4',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cerberus4`,
    },
    vwe_cerberus5 = {
        name = 'Cerberus',
        brand = 'MTL',
        model = 'vwe_cerberus5',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cerberus5`,
    },
    vwe_cheetah1 = {
        name = 'Cheetah',
        brand = 'Grotti',
        model = 'vwe_cheetah1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cheetah1`,
    },
    vwe_club1 = {
        name = 'Club',
        brand = 'BF',
        model = 'vwe_club1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_club1`,
    },
    vwe_cogcabrio1 = {
        name = 'Cognoscenti Cabrio',
        brand = 'Enus',
        model = 'vwe_cogcabrio1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cogcabrio1`,
    },
    vwe_cognoscenti1 = {
        name = 'Cognoscenti',
        brand = 'Enus',
        model = 'vwe_cognoscenti1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_cognoscenti1`,
    },
    vwe_comet1 = {
        name = 'Comet Retro',
        brand = 'Pfister',
        model = 'vwe_comet1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_comet1`,
    },
    vwe_comet2 = {
        name = 'Comet',
        brand = 'Pfister',
        model = 'vwe_comet1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_comet1`,
    },
    vwe_contender1 = {
        name = 'Contender',
        brand = 'Vapid',
        model = 'vwe_contender1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_contender1`,
    },
    vwe_contender2 = {
        name = 'Contender',
        brand = 'Vapid',
        model = 'vwe_contender2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_contender2`,
    },
    vwe_contender3 = {
        name = 'Contender',
        brand = 'Vapid',
        model = 'vwe_contender3',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_contender3`,
    },
    vwe_contender4 = {
        name = 'Contender',
        brand = 'Vapid',
        model = 'vwe_contender4',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_contender4`,
    },
    vwe_contender5 = {
        name = 'Contender',
        brand = 'Vapid',
        model = 'vwe_contender5',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_contender5`,
    },
    vwe_coquette1 = {
        name = 'Coquette',
        brand = 'Invetero',
        model = 'vwe_coquette1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_coquette1`,
    },
    vwe_coquette2 = {
        name = 'Coquette',
        brand = 'Invetero',
        model = 'vwe_coquette2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_coquette2`,
    },
    vwe_coquette3 = {
        name = 'Coquette',
        brand = 'Invetero',
        model = 'vwe_coquette3',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_coquette3`,
    },
    vwe_coyote1 = {
        name = 'Coyote',
        brand = 'Vapid',
        model = 'vwe_coyote1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_coyote1`,
    },
    vwe_coyote2 = {
        name = 'Coyote',
        brand = 'Vapid',
        model = 'vwe_coyote2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_coyote2`,
    },
    vwe_deluxo1 = {
        name = 'Deluxo',
        brand = 'Imponte',
        model = 'vwe_deluxo1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_deluxo1`,
        tier = 'C',
    },
    vwe_dingo1 = {
        name = 'Dingo',
        brand = 'Cheval',
        model = 'vwe_dingo1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_dingo1`,
    },
    vwe_dingo2 = {
        name = 'Dingo',
        brand = 'Cheval',
        model = 'vwe_dingo2',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_dingo2`,
    },
    vwe_dloader1 = {
        name = 'Duneloader',
        brand = 'Bravado',
        model = 'vwe_dloader1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_dloader1`,
    },
    vwe_dominator1 = {
        name = 'Dominator',
        brand = 'Vapid',
        model = 'vwe_dominator1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_dominator1`,
    },
    vwe_dubsta1 = {
        name = 'Dubsta',
        brand = 'Benefactor',
        model = 'vwe_dubsta1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_dubsta1`,
    },
    vwe_dukes1 = {
        name = 'Dukes',
        brand = 'Imponte',
        model = 'vwe_dukes1',
        price = 280000,
        category = 'import',
        type = 'automobile',
        hash = `vwe_dukes1`,
    },

    vwe_juggernaut1 = {
        name = "Juggernaut",
        brand = "JoBuilt",
        price = 56656,
        model = "vwe_juggernaut1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_juggernaut1`,
    },
    vwe_benson1 = {
        name = "Benson",
        brand = "Vapid",
        price = 47273,
        model = "vwe_benson1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_benson1`,
    },
    vweo_es5501 = {
        name = "ES550",
        brand = "Emperor",
        price = 78237,
        model = "vweo_es5501",
        category = "super",
        type = 'automobile',
        hash = `vweo_es5501`,
    },
    vwe_schwartzer2 = {
        name = "Schwartzer",
        brand = "Benefactor",
        price = 69621,
        model = "vwe_schwartzer2",
        category = "coupes",
        type = 'automobile',
        hash = `vwe_schwartzer2`,
    },
    vwe_stdstanier1 = {
        name = "Stanier (STD)",
        brand = "Vapid",
        price = 63587,
        model = "vwe_stdstanier1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_stdstanier1`,
    },
    vwe_tailgater2 = {
        name = "Tailgater",
        brand = "Obey",
        price = 83993,
        model = "vwe_tailgater2",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_tailgater2`,
    },
    vwe_elegy1 = {
        name = "Elegy Classic",
        brand = "Annis",
        price = 78735,
        model = "vwe_elegy1",
        category = "super",
        type = 'automobile',
        hash = `vwe_elegy1`,
    },
    vwe_patriot1 = {
        name = "Patriot",
        brand = "Mammoth",
        price = 63246,
        model = "vwe_patriot1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_patriot1`,
    },
    vwe_steed1 = {
        name = "Steed",
        brand = "Vapid",
        price = 61195,
        model = "vwe_steed1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_steed1`,
    },
    vwe_supergts1 = {
        name = "Super GTS",
        brand = "Dewbauchee",
        price = 87090,
        model = "vwe_supergts1",
        category = "super",
        type = 'automobile',
        hash = `vwe_supergts1`,
        tier = 'X',
    },
    vwe_ruiner2 = {
        name = "Ruiner",
        brand = "Imponte",
        price = 82752,
        model = "vwe_ruiner2",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_ruiner2`,
    },
    vweo_hizoku1 = {
        name = "Hizoku",
        brand = "Annis",
        price = 68838,
        model = "vweo_hizoku1",
        category = "super",
        type = 'automobile',
        hash = `vweo_hizoku1`,
    },
    vwe_sadler6 = {
        name = "Sadler",
        brand = "Vapid",
        price = 58720,
        model = "vwe_sadler6",
        category = "vans",
        type = 'automobile',
        hash = `vwe_sadler6`,
    },
    vwe_granger4 = {
        name = "Granger",
        brand = "Declasse",
        price = 71111,
        model = "vwe_granger4",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_granger4`,
    },
    vweo_emperor1 = {
        name = "Emperor",
        brand = "Albany",
        price = 63587,
        model = "vweo_emperor1",
        category = "sedans",
        type = 'automobile',
        hash = `vweo_emperor1`,
    },
    vwe_yankee2 = {
        name = "Yankee",
        brand = "Vapid",
        price = 49690,
        model = "vwe_yankee2",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_yankee2`,
    },
    vwe_s2301 = {
        name = "S230",
        brand = "Annis",
        price = 66908,
        model = "vwe_s2301",
        category = "super",
        type = 'automobile',
        hash = `vwe_yankee2`,
        tier = 'S',
    },
    vwe_trailerdump1 = {
        name = "Dump Trailer",
        brand = 'Unknown',
        price = 5668,
        model = "vwe_trailerdump1",
        category = "utility",
        type = 'trailer',
        hash = `vwe_trailerdump1`,
    },
    vwe_mammatus1 = {
        name = "Mammatus",
        brand = "JoBuilt",
        price = 1321065,
        model = "vwe_mammatus1",
        category = "planes",
        type = 'plane',
        hash = `vwe_mammatus1`,
    },
    vweo_gauntlet2 = {
        name = "Gauntlet Hellhound",
        brand = "Bravado",
        price = 82106,
        model = "vweo_gauntlet2",
        category = "muscle",
        type = 'automobile',
        hash = `vweo_gauntlet2`,
    },
    vwe_haulmaster1 = {
        name = "Haulmaster",
        brand = "JoBuilt",
        price = 48240,
        model = "vwe_haulmaster1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_haulmaster1`,
    },
    vwe_elena1 = {
        name = "Elena",
        brand = "Ocelot",
        price = 71685,
        model = "vwe_elena1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_elena1`,
    },
    vwe_rancherxl1 = {
        name = "Rancher XL",
        brand = "Declasse",
        price = 68165,
        model = "vwe_rancherxl1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_rancherxl1`,
    },
    vweo_t201 = {
        name = "T20",
        brand = "Progen",
        price = 83022,
        model = "vweo_t201",
        category = "super",
        type = 'automobile',
        hash = `vweo_t201`,
    },
    vwe_templar1 = {
        name = "Templar",
        brand = "LCC",
        price = 25621,
        model = "vwe_templar1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_templar1`,
    },
    vwe_bfinjection1 = {
        name = "Injection",
        brand = "BF",
        price = 72910,
        model = "vwe_bfinjection1",
        category = "offroad",
        type = 'automobile',
        hash = `vwe_bfinjection1`,
    },
    vwe_bobcat3 = {
        name = "Bobcat",
        brand = "Vapid",
        price = 60692,
        model = "vwe_bobcat3",
        category = "vans",
        type = 'automobile',
        hash = `vwe_bobcat3`,
    },
    wardenboat = {
        name = "Rescue Boat",
        brand = "Warden",
        price = 446680,
        model = "wardenboat",
        category = "emergency",
        type = 'boat',
        hash = `wardenboat`,
    },
    vweo_boomerang1 = {
        name = "Boomerang",
        brand = "Cheval",
        price = 91296,
        model = "vweo_boomerang1",
        category = "super",
        type = 'automobile',
        hash = `vweo_boomerang1`,
    },
    vwe_serena1 = {
        name = "Serena",
        brand = "Dinka",
        price = 77424,
        model = "vwe_serena1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_serena1`,
    },
    vwe_rumpo2 = {
        name = "Rumpo",
        brand = "Bravado",
        price = 47273,
        model = "vwe_rumpo2",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_rumpo2`,
    },
    vweo_youga1 = {
        name = "Youga",
        brand = "Bravado",
        price = 85701,
        model = "vweo_youga1",
        category = "vans",
        type = 'automobile',
        hash = `vweo_youga1`,
    },
    vwe_sentinel1 = {
        name = "Sentinel",
        brand = "Ubermacht",
        price = 83392,
        model = "vwe_sentinel1",
        category = "coupes",
        type = 'automobile',
        hash = `vwe_sentinel1`,
    },
    vwe_armordillo1 = {
        name = "Armordillo",
        brand = "HVY",
        price = 59757,
        model = "vwe_armordillo1",
        category = "military",
        type = 'automobile',
        hash = `vwe_armordillo1`,
    },
    vwe_executioner3 = {
        name = "Executioner",
        brand = "Vapid",
        price = 58720,
        model = "vwe_executioner3",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_executioner3`,
    },
    vwe_biff2 = {
        name = "Biff",
        brand = "HVY",
        price = 60714,
        model = "vwe_biff2",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_biff2`,
    },
    vwe_tractor1 = {
        name = "Tractor",
        brand = "Stanley",
        price = 22741,
        model = "vwe_tractor1",
        category = "utility",
        type = 'automobile',
        hash = `vwe_tractor1`,
    },
    vwe_vesper1 = {
        name = "Vesper",
        brand = "Dewbauchee",
        price = 82053,
        model = "vwe_vesper1",
        category = "super",
        type = 'automobile',
        hash = `vwe_vesper1`,
    },
    vweo_kuruma2 = {
        name = "Kuruma",
        brand = "Karin",
        price = 80309,
        model = "vweo_kuruma2",
        category = "super",
        type = 'automobile',
        hash = `vweo_kuruma2`,
    },
    vwe_yosemite4 = {
        name = "Yosemite",
        brand = "Declasse",
        price = 68165,
        model = "vwe_yosemite4",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_yosemite4`,
    },
    vwe_besra1 = {
        name = "Besra",
        brand = "Western",
        price = 35598096,
        model = "vwe_besra1",
        category = "planes",
        type = 'plane',
        hash = `vwe_besra1`,
    },
    vwe_yosemite5 = {
        name = "Yosemite",
        brand = "Declasse",
        price = 68165,
        model = "vwe_yosemite5",
        category = "vans",
        type = 'automobile',
        hash = `vwe_yosemite5`,
    },
    vweo_sbus1 = {
        name = "School Bus",
        brand = "Brute",
        price = 57808,
        model = "vweo_sbus1",
        category = "service",
        type = 'automobile',
        hash = `vweo_sbus1`,
    },
    vwe_stratum1 = {
        name = "Stratum",
        brand = "Zirconium",
        price = 91773,
        model = "vwe_stratum1",
        category = "coupes",
        type = 'automobile',
        hash = `vwe_stratum1`,
    },
    vwe_towtruck1 = {
        name = "Tow Truck",
        brand = "MTL",
        price = 46633,
        model = "vwe_towtruck1",
        category = "emergency",
        type = 'automobile',
        hash = `vwe_towtruck1`,
    },
    vwe_picador1 = {
        name = "Picador",
        brand = "Cheval",
        price = 83008,
        model = "vwe_picador1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_picador1`,
    },
    vweo_packer1 = {
        name = "Packer",
        brand = "MTL",
        price = 83808,
        model = "vweo_packer1",
        category = "super",
        type = 'automobile',
        hash = `vweo_packer1`,
    },
    vwe_vorstand1 = {
        name = "Vorstand",
        brand = "Ubermacht",
        price = 87701,
        model = "vwe_vorstand1",
        category = "super",
        type = 'automobile',
        hash = `vwe_vorstand1`,
    },
    vweo_remower1 = {
        name = "Remower",
        brand = "Jacksheepe",
        price = 82768,
        model = "vweo_remower1",
        category = "muscle",
        type = 'automobile',
        hash = `vweo_remower1`,
    },
    vwe_slasher1 = {
        name = "Slasher",
        brand = "Western",
        price = 23078,
        model = "vwe_slasher1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_slasher1`,
    },
    vwe_packer1 = {
        name = "Packer",
        brand = "MTL",
        price = 60714,
        model = "vwe_packer1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_packer1`,
    },
    vwe_pony1 = {
        name = "Pony",
        brand = "Brute",
        price = 61195,
        model = "vwe_pony1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_pony1`,
    },
    vwe_biff1 = {
        name = "Biff",
        brand = "HVY",
        price = 56668,
        model = "vwe_biff1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_biff1`,
    },
    vwe_torrence1 = {
        name = "Torrence",
        brand = "Vapid",
        price = 60043,
        model = "vwe_torrence1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_torrence1`,
    },
    vweo_lentus1 = {
        name = "Lentus",
        brand = "Declasse",
        price = 77450,
        model = "vweo_lentus1",
        category = "muscle",
        type = 'automobile',
        hash = `vweo_lentus1`,
    },
    vwe_tampa1 = {
        name = "Tampa",
        brand = "Declasse",
        price = 85898,
        model = "vwe_tampa1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_tampa1`,
    },
    vweo_sentinel1 = {
        name = "Sentinel",
        brand = "Ubermacht",
        price = 78202,
        model = "vweo_sentinel1",
        category = "super",
        type = 'automobile',
        hash = `vweo_sentinel1`,
    },
    vwe_utillitruck2 = {
        name = "Utility Truck",
        brand = "Vapid",
        price = 58720,
        model = "vwe_utillitruck2",
        category = "utility",
        type = 'automobile',
        hash = `vwe_utillitruck2`,
    },
    vweo_hizoku2 = {
        name = "Hizoku",
        brand = "Annis",
        price = 68838,
        model = "vweo_hizoku2",
        category = "super",
        type = 'automobile',
        hash = `vweo_hizoku2`,
    },
    vwe_squaddie2 = {
        name = "Squaddie",
        brand = "Mammoth",
        price = 63246,
        model = "vwe_squaddie2",
        category = "military",
        type = 'automobile',
        hash = `vwe_squaddie2`,
    },
    vwe_flatbed1 = {
        name = "Flatbed",
        brand = "MTL",
        price = 59859,
        model = "vwe_flatbed1",
        category = "emergency",
        type = 'automobile',
        hash = `vwe_flatbed1`,
    },
    vwe_zr3501 = {
        name = "ZR350",
        brand = "Annis",
        price = 84734,
        model = "vwe_zr3501",
        category = "super",
        type = 'automobile',
        hash = `vwe_zr3501`,
    },
    vwe_maverick1 = {
        name = "Maverick",
        brand = "Western",
        price = 31465710,
        model = "vwe_maverick1",
        category = "helicopters",
        type = 'heli',
        hash = `vwe_maverick1`,
    },
    vwe_kuroi1 = {
        name = "Kuroi",
        brand = "Dinka",
        price = 24413,
        model = "vwe_kuroi1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_kuroi1`,
    },
    vweo_futo2 = {
        name = "Futo",
        brand = "Karin",
        price = 85914,
        model = "vweo_futo2",
        category = "super",
        type = 'automobile',
        hash = `vweo_futo2`,
    },
    vwe_barracks1 = {
        name = "Barracks",
        brand = "HVY",
        price = 53283,
        model = "vwe_barracks1",
        category = "military",
        type = 'automobile',
        hash = `vwe_barracks1`,
    },
    vwe_infernus1 = {
        name = "Infernus",
        brand = "Pegassi",
        price = 84570,
        model = "vwe_infernus1",
        category = "super",
        type = 'automobile',
        hash = `vwe_infernus1`,
    },
    vwe_urban1 = {
        name = "Urban",
        brand = "Dinka",
        price = 67991,
        model = "vwe_urban1",
        category = "compacts",
        type = 'automobile',
        hash = `vwe_urban1`,
    },
    vwe_stockade1 = {
        name = "Stockade (Bobcat Security/Snow)",
        brand = "Brute",
        price = 56588,
        model = "vwe_stockade1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_stockade1`,
    },
    vwe_sadler1 = {
        name = "Sadler",
        brand = "Vapid",
        price = 72558,
        model = "vwe_sadler1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_sadler1`,
    },
    vwe_raider1 = {
        name = "Raider",
        brand = "Karin",
        price = 63694,
        model = "vwe_raider1",
        category = "offroad",
        type = 'automobile',
        hash = `vwe_raider1`,
    },
    nerossmk2 = {
        name = "Nero SS MK2",
        brand = "Truffade",
        price = 152536,
        model = "nerossmk2",
        category = "super",
        type = 'automobile',
        hash = `nerossmk2`,
    },
    vwe_taxi1 = {
        name = "Taxi",
        brand = "Vapid",
        price = 72718,
        model = "vwe_taxi1",
        category = "service",
        type = 'automobile',
        hash = `vwe_taxi1`,
    },
    vwe_granger2 = {
        name = "Granger",
        brand = "Declasse",
        price = 60692,
        model = "vwe_granger2",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_granger2`,
    },
    vwe_niner1 = {
        name = "9R",
        brand = "Obey",
        price = 85962,
        model = "vwe_niner1",
        category = "super",
        type = 'automobile',
        hash = `vwe_niner1`,
    },
    vweo_vigero1 = {
        name = "Vigero Classic",
        brand = "Declasse",
        price = 77674,
        model = "vweo_vigero1",
        category = "muscle",
        type = 'automobile',
        hash = `vweo_vigero1`,
    },
    vwe_trash1 = {
        name = "Trashmaster",
        brand = "Brute",
        price = 53283,
        model = "vwe_trash1",
        category = "service",
        type = 'automobile',
        hash = `vwe_trash1`,
    },
    vweo_zr3801 = {
        name = "ZR380",
        brand = "Annis",
        price = 83632,
        model = "vweo_zr3801",
        category = "super",
        type = 'automobile',
        hash = `vweo_zr3801`,
    },
    vweo_fmjgte1 = {
        name = "FMJ GTE",
        brand = "Vapid",
        price = 84378,
        model = "vweo_fmjgte1",
        category = "super",
        type = 'automobile',
        hash = `vweo_fmjgte1`,
        tier = 'X',
    },
    vwe_vigero1 = {
        name = "Vigero",
        brand = "Declasse",
        price = 77482,
        model = "vwe_vigero1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_vigero1`,
    },
    vwe_majimagt1 = {
        name = "Maji",
        brand = "Annis",
        price = 85878,
        model = "vwe_majimagt1",
        category = "super",
        type = 'automobile',
        hash = `vwe_majimagt1`,
    },
    vwe_youga1 = {
        name = "Youga",
        brand = "Bravado",
        price = 71701,
        model = "vwe_youga1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_youga1`,
    },
    vwe_feroci1 = {
        name = "Feroci",
        brand = "Bravado",
        price = 93386,
        model = "vwe_feroci1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_feroci1`,
    },
    vweo_7111 = {
        name = "711",
        brand = "Pfister",
        price = 99888,
        model = "vweo_7111",
        category = "super",
        type = 'automobile',
        hash = `vweo_7111`,
    },
    vwe_steed3 = {
        name = "Steed",
        brand = "Vapid",
        price = 47273,
        model = "vwe_steed3",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_steed3`,
    },
    vwe_elegy2 = {
        name = "Elegy",
        brand = "Annis",
        price = 81290,
        model = "vwe_elegy2",
        category = "super",
        type = 'automobile',
        hash = `vwe_elegy2`,
    },
    vwe_ruiner1 = {
        name = "Ruiner",
        brand = "Imponte",
        price = 82885,
        model = "vwe_ruiner1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_ruiner1`,
    },
    vwe_executioner1 = {
        name = "Executioner",
        brand = "Vapid",
        price = 70697,
        model = "vwe_executioner1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_executioner1`,
    },
    vwe_greenwood1 = {
        name = "Greenwood",
        brand = "Schyster",
        price = 63587,
        model = "vwe_greenwood1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_greenwood1`,
    },
    vwe_seminole1 = {
        name = "Seminole",
        brand = "Canis",
        price = 75714,
        model = "vwe_seminole1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_seminole1`,
    },
    vweo_issi1 = {
        name = "Issi",
        brand = "Weeny",
        price = 71791,
        model = "vweo_issi1",
        category = "compacts",
        type = 'automobile',
        hash = `vweo_issi1`,
    },
    vwe_rebel4 = {
        name = "Rebel",
        brand = "Karin",
        price = 63694,
        model = "vwe_rebel4",
        category = "offroad",
        type = 'automobile',
        hash = `vwe_rebel4`,
    },
    vweo_verlierer1 = {
        name = "Verlierer",
        brand = "Bravado",
        price = 74052,
        model = "vweo_verlierer1",
        category = "super",
        type = 'automobile',
        hash = `vweo_verlierer1`,
    },
    vwe_trailerdump2 = {
        name = "Dump Trailer",
        brand = "Unknown",
        price = 5668,
        model = "vwe_trailerdump2",
        category = "utility",
        type = 'trailer',
        hash = `vwe_trailerdump2`,
    },
    vwe_golem1 = {
        name = "Golem",
        brand = "Western",
        price = 25195,
        model = "vwe_golem1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_golem1`,
    },
    vwe_tyrus1 = {
        name = "Tyrus",
        brand = "Progen",
        price = 84350,
        model = "vwe_tyrus1",
        category = "super",
        type = 'automobile',
        hash = `vwe_tyrus1`,
    },
    vwe_warrener1 = {
        name = "Warrener",
        brand = "Vulcar",
        price = 81107,
        model = "vwe_warrener1",
        category = "coupes",
        type = 'automobile',
        hash = `vwe_warrener1`,
    },
    vwe_yosemite2 = {
        name = "Yosemite",
        brand = "Declasse",
        price = 60692,
        model = "vwe_yosemite2",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_yosemite2`,
    },
    vwe_seraph1 = {
        name = "Seraph",
        brand = "Ubermacht",
        price = 76907,
        model = "vwe_seraph1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_seraph1`,
    },
    vwe_trailercast1 = {
        name = "Cast Trailer",
        brand = "Albany",
        price = 530467,
        model = "vwe_trailercast1",
        category = "utility",
        type = 'trailer',
        hash = `vwe_trailercast1`,
    },
    vwe_streiter1 = {
        name = "Streiter",
        brand = "Benefactor",
        price = 71204,
        model = "vwe_streiter1",
        category = "super",
        type = 'automobile',
        hash = `vwe_streiter1`,
    },
    vwe_stratum2 = {
        name = "Stratum",
        brand = "Zirconium",
        price = 83544,
        model = "vwe_stratum2",
        category = "super",
        type = 'automobile',
        hash = `vwe_stratum2`,
    },
    vwe_surfer1 = {
        name = "Surfer",
        brand = "BF",
        price = 49770,
        model = "vwe_surfer1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_surfer1`,
    },
    vwe_lazer1 = {
        name = "Lazer",
        brand = "Unknown",
        price = 2374070,
        model = "vwe_lazer1",
        category = "planes",
        type = 'plane',
        hash = `vwe_lazer1`,
    },
    vwe_hauler1 = {
        name = "Hauler",
        brand = "JoBuilt",
        price = 55056,
        model = "vwe_hauler1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_hauler1`,
    },
    vwe_kuruma1 = {
        name = "Kuruma",
        brand = "Karin",
        price = 77445,
        model = "vwe_kuruma1",
        category = "super",
        type = 'automobile',
        hash = `vwe_kuruma1`,
    },
    vweo_picador1 = {
        name = "Picador",
        brand = "Cheval",
        price = 86314,
        model = "vweo_picador1",
        category = "muscle",
        type = 'automobile',
        hash = `vweo_picador1`,
    },
    vweo_rapidgte1 = {
        name = "Rapid GTE",
        brand = "Dewbauchee",
        price = 85583,
        model = "vweo_rapidgte1",
        category = "super",
        type = 'automobile',
        hash = `vweo_rapidgte1`,
    },
    vwe_radi1 = {
        name = "Radius",
        brand = "Vapid",
        price = 69969,
        model = "vwe_radi1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_radi1`,
    },
    vwe_jester1 = {
        name = "Jester",
        brand = "Dinka",
        price = 80462,
        model = "vwe_jester1",
        category = "super",
        type = 'automobile',
        hash = `vwe_jester1`,
        tier = 'S',
    },
    vwe_phantom1 = {
        name = "Phantom",
        brand = "JoBuilt",
        price = 56656,
        model = "vwe_phantom1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_phantom1`,
    },
    vwe_hachura1 = {
        name = "Hachura",
        brand = "Vulcar",
        price = 83200,
        model = "vwe_hachura1",
        category = "super",
        type = 'automobile',
        hash = `vwe_hachura1`,
        tier = 'S',
    },
    vwe_riata1 = {
        name = "Riata",
        brand = "Vapid",
        price = 58720,
        model = "vwe_riata1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_riata1`,
    },
    vwe_tanker2 = {
        name = "Tanker",
        brand = "Unknown",
        price = 5749,
        model = "vwe_tanker2",
        category = "utility",
        type = 'trailer',
        hash = `vwe_tanker2`,
    },
    vwe_rom1 = {
        name = "Esperanto",
        brand = "Albany",
        price = 71053,
        model = "vwe_rom1",
        category = "service",
        type = 'automobile',
        hash = `vwe_rom1`,
    },
    watertanker = {
        name = "Trailer (Container)",
        brand = "Unknown",
        price = 5749,
        model = "watertanker",
        category = "utility",
        type = 'trailer',
        hash = `watertanker`,
    },
    vwe_hades1 = {
        name = "Hades",
        brand = "Zirconium",
        price = 78720,
        model = "vwe_hades1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_hades1`,
    },
    wheelchair = {
        name = "Wheelchair",
        brand = "Brute",
        price = 4588,
        model = "wheelchair",
        category = "offroad",
        type = 'automobile',
        hash = `wheelchair`,
    },
    vwe_uranus1 = {
        name = "Uranus",
        brand = "Vapid",
        price = 76906,
        model = "vwe_uranus1",
        category = "super",
        type = 'automobile',
        hash = `vwe_uranus1`,
    },
    vwe_journey1 = {
        name = "Journey",
        brand = "Zirconium",
        price = 54757,
        model = "vwe_journey1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_journey1`,
    },
    vwe_annihilator1 = {
        name = "Annihilator",
        brand = "Western",
        price = 26390295,
        model = "vwe_annihilator1",
        category = "helicopters",
        type = 'heli',
        hash = `vwe_annihilator1`,
    },
    vwe_zr1501 = {
        name = "ZR150",
        brand = "Annis",
        price = 82592,
        model = "vwe_zr1501",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_zr1501`,
    },
    vwe_stanier1 = {
        name = "Stanier",
        brand = "Vapid",
        price = 72718,
        model = "vwe_stanier1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_stanier1`,
    },
    vwe_scout1 = {
        name = "Scout",
        brand = "Vapid",
        price = 74384,
        model = "vwe_scout1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_scout1`,
    },
    vwe_yosemite3 = {
        name = "Yosemite",
        brand = "Declasse",
        price = 68165,
        model = "vwe_yosemite3",
        category = "vans",
        type = 'automobile',
        hash = `vwe_yosemite3`,
    },
    vwe_cartrailer2 = {
        name = "Car Trailer",
        brand = "Unknown",
        price = 5668,
        model = "vwe_cartrailer2",
        category = "utility",
        type = 'trailer',
        hash = `vwe_cartrailer2`,
    },
    vwe_blade1 = {
        name = "Blade",
        brand = "Vapid",
        price = 70520,
        model = "vwe_blade1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_blade1`,
    },
    vwe_boattrailer1 = {
        name = "Boat Trailer",
        brand = "Unknown",
        price = 5668,
        model = "vwe_boattrailer1",
        category = "utility",
        type = 'trailer',
        hash = `vwe_boattrailer1`,
    },
    vwe_sandking1 = {
        name = "Sandking",
        brand = "Vapid",
        price = 62297,
        model = "vwe_sandking1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_sandking1`,
    },
    vwe_cartrailer1 = {
        name = "Car Trailer",
        brand = "Unknown",
        price = 5668,
        model = "vwe_cartrailer1",
        category = "utility",
        type = 'trailer',
        hash = `vwe_cartrailer1`,
    },
    vweo_deluxo1 = {
        name = "Deluxo",
        brand = "Imponte",
        price = 70738,
        model = "vweo_deluxo1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vweo_deluxo1`,
    },
    vwe_sadler5 = {
        name = "Sadler",
        brand = "Vapid",
        price = 58720,
        model = "vwe_sadler5",
        category = "vans",
        type = 'automobile',
        hash = `vwe_sadler5`,
    },
    vwe_dukes2 = {
        name = "Dukes",
        brand = "Imponte",
        price = 75100,
        model = "vwe_dukes2",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_dukes2`,
    },
    vwe_esperanto1 = {
        name = "Esperanto",
        brand = "Albany",
        price = 71053,
        model = "vwe_esperanto1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_esperanto1`,
    },
    vwe_euphoria1 = {
        name = "Euphoria",
        brand = "Ocelot",
        price = 77601,
        model = "vwe_euphoria1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_euphoria1`,
    },
    vwe_tulip1 = {
        name = "Tulip",
        brand = "Declasse",
        price = 80611,
        model = "vwe_tulip1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_tulip1`,
    },
    vwe_euros1 = {
        name = "Euros",
        brand = "Annis",
        price = 79383,
        model = "vwe_euros1",
        category = "coupes",
        type = 'automobile',
        hash = `vwe_euros1`,
        tier = 'S',
    },
    vwe_executioner2 = {
        name = "Executioner",
        brand = "Vapid",
        price = 58720,
        model = "vwe_executioner2",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_executioner2`,
    },
    vwe_fugitive1 = {
        name = "Fugitive",
        brand = "Cheval",
        price = 85295,
        model = "vwe_fugitive1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_fugitive1`,
    },
    vwe_issi1 = {
        name = "Issi",
        brand = "Weeny",
        price = 80867,
        model = "vwe_issi1",
        category = "compacts",
        type = 'automobile',
        hash = `vwe_issi1`,
    },
    vwe_glendale1 = {
        name = "Glendale",
        brand = "Benefactor",
        price = 83353,
        model = "vwe_glendale1",
        category = "coupes",
        type = 'automobile',
        hash = -1648658016,
    },
    vwe_glendale2 = {
        name = "Glendale",
        brand = "Benefactor",
        price = 86805,
        model = "vwe_glendale2",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_glendale2`,
    },
    vwe_limo1 = {
        name = "Limo",
        brand = "Benefactor",
        price = 54176,
        model = "vwe_limo1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_limo1`,
    },
    vwe_granger1 = {
        name = "Granger",
        brand = "Declasse",
        price = 75714,
        model = "vwe_granger1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_granger1`,
    },
    vwe_granger3 = {
        name = "Granger",
        brand = "Declasse",
        price = 60692,
        model = "vwe_granger3",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_granger3`,
    },
    vwe_gresley1 = {
        name = "Gresley Hellhound",
        brand = "Bravado",
        price = 79618,
        model = "vwe_gresley1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_gresley1`,
    },
    vwe_haulmaster2 = {
        name = "Haulmaster",
        brand = "JoBuilt",
        price = 48240,
        model = "vwe_haulmaster2",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_haulmaster2`,
    },
    vwe_hellion1 = {
        name = "Hellion",
        brand = "Annis",
        price = 62297,
        model = "vwe_hellion1",
        category = "offroad",
        type = 'automobile',
        hash = `vwe_hellion1`,
    },
    vwe_infernus2 = {
        name = "Infernus",
        brand = "Pegassi",
        price = 99059,
        model = "vwe_infernus2",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_infernus2`,
    },
    vwe_kenshin1 = {
        name = "Kenshin",
        brand = "Nagasaki",
        price = 24649,
        model = "vwe_kenshin1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_kenshin1`,
    },
    vwe_landroamer1 = {
        name = "Landroamer",
        brand = "Dundreary",
        price = 73366,
        model = "vwe_landroamer1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_landroamer1`,
    },
    vwe_longpath1 = {
        name = "Longpath",
        brand = "JoBuilt",
        price = 48240,
        model = "vwe_longpath1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_longpath1`,
    },
    vwe_merit1 = {
        name = "Merit",
        brand = "Declasse",
        price = 77450,
        model = "vwe_merit1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_merit1`,
    },
    vwe_mesa1 = {
        name = "Mesa",
        brand = "Canis",
        price = 72878,
        model = "vwe_mesa1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_mesa1`,
    },
    vwe_mesa2 = {
        name = "Mesa",
        brand = "Canis",
        price = 72878,
        model = "vwe_mesa2",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_mesa2`,
    },
    vwe_meteor1 = {
        name = "Meteor",
        brand = "Pfister",
        price = 86205,
        model = "vwe_meteor1",
        category = "super",
        type = 'automobile',
        hash = `vwe_meteor1`,
        tier = 'X',
    },
    vwe_mf1 = {
        name = "MF1",
        brand = "Progen",
        price = 83773,
        model = "vwe_mf1",
        category = "super",
        type = 'automobile',
        hash = `vwe_mf1`,
    },
    vwe_mf12 = {
        name = "MF1",
        brand = "Progen",
        price = 85074,
        model = "vwe_mf12",
        category = "super",
        type = 'automobile',
        hash = `vwe_mf12`,
    },
    vwe_minivan1 = {
        name = "Minivan",
        brand = "Vapid",
        price = 63267,
        model = "vwe_minivan1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_minivan1`,
    },
    vwe_mixer1 = {
        name = "Mixer",
        brand = "Brute",
        price = 53283,
        model = "vwe_mixer1",
        category = "industrial",
        type = 'automobile',
        hash = `vwe_mixer1`,
    },
    vwe_molecule1 = {
        name = "Molecule",
        brand = "Maxwell",
        price = 85462,
        model = "vwe_molecule1",
        category = "super",
        type = 'automobile',
        hash = -951905493,
    },
    vwe_monroe1 = {
        name = "Monroe",
        brand = "Pegassi",
        price = 83728,
        model = "vwe_monroe1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_monroe1`,
        tier = 'S',
    },
    vwe_moonbeam1 = {
        name = "Moonbeam",
        brand = "Declasse",
        price = 63253,
        model = "vwe_moonbeam1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_moonbeam1`,
    },
    vwe_mule1 = {
        name = "Mule",
        brand = "Maibatsu",
        price = 53203,
        model = "vwe_mule1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_mule1`,
    },
    vwe_mule2 = {
        name = "Mule",
        brand = "Maibatsu",
        price = 44967,
        model = "vwe_mule2",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_mule2`,
    },
    vwe_regina1 = {
        name = "Regina",
        brand = "Dundreary",
        price = 50677,
        model = "vwe_regina1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_regina1`,
        tier = 'D',
    },
    vwe_ramptruck1 = {
        name = "Ramp Truck",
        brand = "Declasse",
        price = 75714,
        model = "vwe_ramptruck1",
        category = "service",
        type = 'automobile',
        hash = `vwe_ramptruck1`,
    },
    vwe_mule3 = {
        name = "Mule",
        brand = "Maibatsu",
        price = 44967,
        model = "vwe_mule3",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_mule3`,
    },
    vwe_mule4 = {
        name = "Mule",
        brand = "Maibatsu",
        price = 64344,
        model = "vwe_mule4",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_mule4`,
    },
    vwe_nebula1 = {
        name = "Nebula",
        brand = "Vulcar",
        price = 62893,
        model = "vwe_nebula1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_nebula1`,
    },
    vwe_nebula2 = {
        name = "Nebula",
        brand = "Vulcar",
        price = 62877,
        model = "vwe_nebula2",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_nebula2`,
    },
    vwe_panto1 = {
        name = "Panto",
        brand = "Benefactor",
        price = 76786,
        model = "vwe_panto1",
        category = "compacts",
        type = 'automobile',
        hash = `vwe_panto1`,
    },
    vwe_sultan2 = {
        name = "Sultan",
        brand = "Karin",
        price = 82197,
        model = "vwe_sultan2",
        category = "super",
        type = 'automobile',
        hash = `vwe_sultan2`,
    },
    vwe_patriot2 = {
        name = "Patriot",
        brand = "Mammoth",
        price = 63246,
        model = "vwe_patriot2",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_patriot2`,
    },
    vwe_picador2 = {
        name = "Picador",
        brand = "Cheval",
        price = 81048,
        model = "vwe_picador2",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_picador2`,
    },
    vwe_pony2 = {
        name = "Pony",
        brand = "Brute",
        price = 61195,
        model = "vwe_pony2",
        category = "vans",
        type = 'automobile',
        hash = `vwe_pony2`,
    },
    vwe_pounder1 = {
        name = "Pounder",
        brand = "MTL",
        price = 55550,
        model = "vwe_pounder1",
        category = "industrial",
        type = 'automobile',
        hash = `vwe_pounder1`,
    },
    vwe_ramptruck2 = {
        name = "Ramp Truck",
        brand = "Vapid",
        price = 72558,
        model = "vwe_ramptruck2",
        category = "utility",
        type = 'automobile',
        hash = -`vwe_ramptruck2`,
    },
    vwe_trailers2 = {
        name = "Trailer",
        brand = "Unknown",
        price = 5668,
        model = "vwe_trailers2",
        category = "utility",
        type = 'trailer',
        hash = `vwe_trailers2`,
    },
    vwe_rancher1 = {
        name = "Rancher",
        brand = "Declasse",
        price = 68165,
        model = "vwe_rancher1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_rancher1`,
    },
    vwe_rancher2 = {
        name = "Rancher",
        brand = "Declasse",
        price = 68165,
        model = "vwe_rancher2",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_rancher2`,
    },
    vwe_rancher3 = {
        name = "Rancher",
        brand = "Declasse",
        price = 68165,
        model = "vwe_rancher3",
        category = "vans",
        type = 'automobile',
        hash = `vwe_rancher3`,
    },
    vwe_seminole2 = {
        name = "Seminole",
        brand = "Canis",
        price = 75714,
        model = "vwe_seminole2",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_seminole2`,
    },
    vwe_ratloader1 = {
        name = "Rat-Loader",
        brand = "Bravado",
        price = 79202,
        model = "vwe_ratloader1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_ratloader1`,
    },
    vwe_razor1 = {
        name = "Razor",
        brand = "Vapid",
        price = 77450,
        model = "vwe_razor1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_razor1`,
    },
    vwe_rebel1 = {
        name = "Rebel",
        brand = "Karin",
        price = 81187,
        model = "vwe_rebel1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_rebel1`,
    },
    vwe_rebel2 = {
        name = "Rebel",
        brand = "Karin",
        price = 63694,
        model = "vwe_rebel2",
        category = "offroad",
        type = 'automobile',
        hash = `vwe_rebel2`,
    },
    vwe_rebel3 = {
        name = "Rebel",
        brand = "Karin",
        price = 63694,
        model = "vwe_rebel3",
        category = "offroad",
        type = 'automobile',
        hash = `vwe_rebel3`,
    },
    vwe_recursion1 = {
        name = "Recursion",
        brand = "Bravado",
        price = 80117,
        model = "vwe_recursion1",
        category = "super",
        type = 'automobile',
        hash = `vwe_recursion1`,
    },
    vwe_riata2 = {
        name = "Riata",
        brand = "Vapid",
        price = 58720,
        model = "vwe_riata2",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_riata2`,
    },
    vwe_riata3 = {
        name = "Riata",
        brand = "Vapid",
        price = 69535,
        model = "vwe_riata3",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_riata3`,
    },
    vwe_roadkiller1 = {
        name = "Roadkiller",
        brand = "Brute",
        price = 60714,
        model = "vwe_roadkiller1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_roadkiller1`,
    },
    vwe_rumpo1 = {
        name = "Rumpo",
        brand = "Bravado",
        price = 72238,
        model = "vwe_rumpo1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_rumpo1`,
    },
    vwe_sabot1 = {
        name = "Sabot",
        brand = "Vapid",
        price = 87306,
        model = "vwe_sabot1",
        category = "super",
        type = 'automobile',
        hash = `vwe_sabot1`,
    },
    vwe_sadler2 = {
        name = "Sadler",
        brand = "Vapid",
        price = 58720,
        model = "vwe_sadler2",
        category = "vans",
        type = 'automobile',
        hash = `vwe_sadler2`,
    },
    vwe_sadler3 = {
        name = "Sadler",
        brand = "Vapid",
        price = 58720,
        model = "vwe_sadler3",
        category = "vans",
        type = 'automobile',
        hash = `vwe_sadler3`,
    },
    vwe_sadler4 = {
        name = "Sadler",
        brand = "Vapid",
        price = 58720,
        model = "vwe_sadler4",
        category = "vans",
        type = 'automobile',
        hash = `vwe_sadler4`,
    },
    vwe_sadler7 = {
        name = "Sadler",
        brand = "Vapid",
        price = 58720,
        model = "vwe_sadler7",
        category = "vans",
        type = 'automobile',
        hash = `vwe_sadler7`,
    },
    vwe_sandking2 = {
        name = "Sandking",
        brand = "Vapid",
        price = 68971,
        model = "vwe_sandking2",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_sandking2`,
    },
    vwe_savestra1 = {
        name = "Savestra",
        brand = "Annis",
        price = 74551,
        model = "vwe_savestra1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_savestra1`,
    },
    vwe_sbus1 = {
        name = "School Bus",
        brand = "Brute",
        price = 49187,
        model = "vwe_sbus1",
        category = "service",
        type = 'automobile',
        hash = `vwe_sbus1`,
    },
    vwe_sbus2 = {
        name = "School Bus",
        brand = "Brute",
        price = 49647,
        model = "vwe_sbus2",
        category = "service",
        type = 'automobile',
        hash = `vwe_sbus2`,
    },
    vwe_scamp1 = {
        name = "Scamp",
        brand = "Mammoth",
        price = 1702472,
        model = "vwe_scamp1",
        category = "planes",
        type = 'plane',
        hash = `vwe_scamp1`,
    },
    vwe_schwartzer1 = {
        name = "Schwartzer",
        brand = "Benefactor",
        price = 69621,
        model = "vwe_schwartzer1",
        category = "coupes",
        type = 'automobile',
        hash = `vwe_schwartzer1`,
    },
    vwe_sigma2 = {
        name = "Sigma",
        brand = "Karin",
        price = 82821,
        model = "vwe_sigma2",
        category = "super",
        type = 'automobile',
        hash = `vwe_sigma2`,
    },
    vwe_sigma3 = {
        name = "Sigma",
        brand = "Karin",
        price = 77585,
        model = "vwe_sigma3",
        category = "super",
        type = 'automobile',
        hash = `vwe_sigma3`,
    },
    vwe_slamvan1 = {
        name = "Slamvan",
        brand = "Vapid",
        price = 90352,
        model = "vwe_slamvan1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_slamvan1`,
    },
    vwe_slave1 = {
        name = "Slave",
        brand = "Western",
        price = 23182,
        model = "vwe_slave1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_slave1`,
    },
    vwe_sparrow1 = {
        name = "Sparrow",
        brand = "Unknown",
        price = 6293142,
        model = "vwe_sparrow1",
        category = "helicopters",
        type = 'heli',
        hash = `vwe_sparrow1`,
    },
    vwe_speedo1 = {
        name = "Speedo",
        brand = "Vapid",
        price = 47273,
        model = "vwe_speedo1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_speedo1`,
    },
    vwe_speedo2 = {
        name = "Speedo",
        brand = "Vapid",
        price = 81161,
        model = "vwe_speedo2",
        category = "vans",
        type = 'automobile',
        hash = `vwe_speedo2`,
    },
    vwe_spirit1 = {
        name = "Spirit",
        brand = "Western",
        price = 23582,
        model = "vwe_spirit1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_spirit1`,
    },
    vwe_spritzer1 = {
        name = "Spritzer",
        brand = "Benefactor",
        price = 78839,
        model = "vwe_spritzer1",
        category = "super",
        type = 'automobile',
        hash = `vwe_spritzer1`,
    },
    vwe_squaddie1 = {
        name = "Squaddie",
        brand = "Mammoth",
        price = 316231,
        model = "vwe_squaddie1",
        category = "military",
        type = 'automobile',
        hash = `vwe_squaddie1`,
    },
    vwe_steed2 = {
        name = "Steed",
        brand = "Vapid",
        price = 59287,
        model = "vwe_steed2",
        category = "vans",
        type = 'automobile',
        hash = `vwe_steed2`,
    },
    vwe_stretch1 = {
        name = "Stretch",
        brand = "Albany",
        price = 63951,
        model = "vwe_stretch1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_stretch1`,
    },
    vwe_sultan1 = {
        name = "Sultan",
        brand = "Karin",
        price = 83300,
        model = "vwe_sultan1",
        category = "super",
        type = 'automobile',
        hash = `vwe_sultan1`,
    },
    vwe_sultanrs1 = {
        name = "Sultan RS",
        brand = "Karin",
        price = 82197,
        model = "vwe_sultanrs1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_sultanrs1`,
    },
    vwe_sultanrs2 = {
        name = "Sultan RS",
        brand = "Karin",
        price = 82197,
        model = "vwe_sultanrs2",
        category = "super",
        type = 'automobile',
        hash = `vwe_sultanrs2`,
    },
    vwe_sultanrs3 = {
        name = "Sultan RS",
        brand = "Karin",
        price = 82197,
        model = "vwe_sultanrs3",
        category = "super",
        type = 'automobile',
        hash = `vwe_sultanrs3`,
    },
    vwe_surano1 = {
        name = "Surano",
        brand = "Benefactor",
        price = 96693,
        model = "vwe_surano1",
        category = "super",
        type = 'automobile',
        hash = `vwe_surano1`,
    },
    vwe_surge1 = {
        name = "Surge",
        brand = "Cheval",
        price = 66592,
        model = "vwe_surge1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_surge1`,
    },
    vwe_tachyon1 = {
        name = "Tachyon",
        brand = "Hijak",
        price = 83018,
        model = "vwe_tachyon1",
        category = "super",
        type = 'automobile',
        hash = `vwe_tachyon1`,
    },
    vwe_tailgater1 = {
        name = "Tailgater",
        brand = "Obey",
        price = 57435,
        model = "vwe_tailgater1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_tailgater1`,
    },
    vwe_tailgater3 = {
        name = "Tailgater",
        brand = "Obey",
        price = 73446,
        model = "vwe_tailgater3",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_tailgater3`,
    },
    vwe_tanker1 = {
        name = "Tanker",
        brand = "Unknown",
        price = 5749,
        model = "vwe_tanker1",
        category = "utility",
        type = 'trailer',
        hash = `vwe_tanker1`,
    },
    vwe_tr1 = {
        name = "Construction Trailer",
        brand = "Unknown",
        price = 5749,
        model = "vwe_tr1",
        category = "utility",
        type = 'trailer',
        hash = `vwe_tr1`,
    },
    vwe_trailers1 = {
        name = "Trailer",
        brand = "Unknown",
        price = 5668,
        model = "vwe_trailers1",
        category = "utility",
        type = 'trailer',
        hash = `vwe_trailers1`,
    },
    vwe_trailers3 = {
        name = "Trailer",
        brand = "Unknown",
        price = 5668,
        model = "vwe_trailers3",
        category = "utility",
        type = 'trailer',
        hash = `vwe_trailers3`,
    },
    vwe_trailerdump3 = {
        name = "Dump Trailer",
        brand = "Unknown",
        price = 5668,
        model = "vwe_trailerdump3",
        category = "utility",
        type = 'trailer',
        hash = `vwe_trailerdump3`,
    },
    vwe_trailerlogs1 = {
        name = "Log Trailer",
        brand = "Unknown",
        price = 5749,
        model = "vwe_trailerlogs1",
        category = "utility",
        type = 'trailer',
        hash = `vwe_trailerlogs1`,
    },
    vwe_turismo1 = {
        name = "Turismo",
        brand = "Grotti",
        price = 86168,
        model = "vwe_turismo1",
        category = "super",
        type = 'automobile',
        hash = `vwe_turismo1`,
    },
    vwe_utillitruck1 = {
        name = "Utility Truck",
        brand = "Vapid",
        price = 58400,
        model = "vwe_utillitruck1",
        category = "utility",
        type = 'automobile',
        hash = `vwe_utillitruck1`,
    },
    vwe_utillitruck3 = {
        name = "Utility Truck",
        brand = "Vapid",
        price = 58720,
        model = "vwe_utillitruck3",
        category = "utility",
        type = 'automobile',
        hash = `vwe_utillitruck3`,
    },
    vwe_ventoso1 = {
        name = "Ventoso",
        brand = "Dinka",
        price = 12690,
        model = "vwe_ventoso1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_ventoso1`,
    },
    vwe_verin1 = {
        name = "Verin",
        brand = "LCC",
        price = 23182,
        model = "vwe_verin1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_verin1`,
    },
    vwe_vertice1 = {
        name = "Vertice",
        brand = "Hijak",
        price = 85888,
        model = "vwe_vertice1",
        category = "super",
        type = 'automobile',
        hash = `vwe_vertice1`,
    },
    vwe_vincent1 = {
        name = "Vincent",
        brand = "Maibatsu",
        price = 75211,
        model = "vwe_vincent1",
        category = "super",
        type = 'automobile',
        hash = `vwe_vincent1`,
    },
    vwe_voodoo1 = {
        name = "Voodoo",
        brand = "Declasse",
        price = 59072,
        model = "vwe_voodoo1",
        category = "muscle",
        type = 'automobile',
        hash = `vwe_voodoo1`,
    },
    vwe_washington1 = {
        name = "Washington",
        brand = "Albany",
        price = 80963,
        model = "vwe_washington1",
        category = "sedans",
        type = 'automobile',
        hash = `vwe_washington1`,
    },
    vwe_watertanker1 = {
        name = "Water Tanker",
        brand = "Unknown",
        price = 5749,
        model = "vwe_watertanker1",
        category = "utility",
        type = 'trailer',
        hash = `vwe_watertanker1`,
    },
    vwe_wintergreen1 = {
        name = "Wintergreen",
        brand = "Western",
        price = 23078,
        model = "vwe_wintergreen1",
        category = "motorcycles",
        type = 'bike',
        hash = `vwe_wintergreen1`,
    },
    vwe_yankee1 = {
        name = "Yankee",
        brand = "Vapid",
        price = 57365,
        model = "vwe_yankee1",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_yankee1`,
    },
    vwe_yankee3 = {
        name = "Yankee",
        brand = "Vapid",
        price = 49690,
        model = "vwe_yankee3",
        category = "commercial",
        type = 'automobile',
        hash = `vwe_yankee3`,
    },
    vwe_yosemite1 = {
        name = "Yosemite",
        brand = "Declasse",
        price = 75714,
        model = "vwe_yosemite1",
        category = "vans",
        type = 'automobile',
        hash = `vwe_yosemite1`,
    },
    vwe_yosemitexl1 = {
        name = "Yosemite XL",
        brand = "Declasse",
        price = 68165,
        model = "vwe_yosemitexl1",
        category = "suvs",
        type = 'automobile',
        hash = `vwe_yosemitexl1`,
    },
    vwe_yosemitexl2 = {
        name = "Yosemite XL",
        brand = "Declasse",
        price = 68165,
        model = "vwe_yosemitexl2",
        category = "vans",
        type = 'automobile',
        hash = `vwe_yosemitexl2`,
    },
    vwe_zion1 = {
        name = "Zion",
        brand = "Ubermacht",
        price = 77766,
        model = "vwe_zion1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_zion1`,
    },
    vwe_zion2 = {
        name = "Zion",
        brand = "Ubermacht",
        price = 82666,
        model = "vwe_zion2",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vwe_zion2`,
    },
    vwe_zr3801 = {
        name = "ZR380",
        brand = "Annis",
        price = 83632,
        model = "vwe_zr3801",
        category = "super",
        type = 'automobile',
        hash = `vwe_zr3801`,
        tier = 'S',
    },
    vweo_ardent1 = {
        name = "Ardent",
        brand = "Ocelot",
        price = 930748,
        model = "vweo_ardent1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vweo_ardent1`,
    },
    vweo_blista1 = {
        name = "Blista",
        brand = "Dinka",
        price = 84634,
        model = "vweo_blista1",
        category = "super",
        type = 'automobile',
        hash = `vweo_blista1`,
    },
    vweo_cw20201 = {
        name = "2020",
        brand = "CW",
        price = 94253,
        model = "vweo_cw20201",
        category = "openwheel",
        type = 'automobile',
        hash = `vweo_cw20201`,
    },
    vweo_dukes1 = {
        name = "Dukes",
        brand = "Imponte",
        price = 80819,
        model = "vweo_dukes1",
        category = "muscle",
        type = 'automobile',
        hash = `vweo_dukes1`,
    },
    vweo_elegy1 = {
        name = "Elegy (Beater)",
        brand = "Annis",
        price = 78735,
        model = "vweo_elegy1",
        category = "super",
        type = 'automobile',
        hash = `vweo_elegy1`,
    },
    vweo_elegy2 = {
        name = "Elegy RH8 (Beater)",
        brand = "Annis",
        price = 78735,
        model = "vweo_elegy2",
        category = "super",
        type = 'automobile',
        hash = `vweo_elegy2`,
    },
    vweo_elegy3 = {
        name = "Elegy (Grand Touring)",
        brand = "Annis",
        price = 78735,
        model = "vweo_elegy3",
        category = "super",
        type = 'automobile',
        hash = `vweo_elegy3`,
    },
    vweo_flash1 = {
        name = "Flash",
        brand = "Dinka",
        price = 69291,
        model = "vweo_flash1",
        category = "compacts",
        type = 'automobile',
        hash = `vweo_flash1`,
    },
    vweo_fugitive1 = {
        name = "Fugitive",
        brand = "Cheval",
        price = 80590,
        model = "vweo_fugitive1",
        category = "super",
        type = 'automobile',
        hash = `vweo_fugitive1`,
    },
    vweo_futo1 = {
        name = "Futo",
        brand = "Karin",
        price = 74336,
        model = "vweo_futo1",
        category = "super",
        type = 'automobile',
        hash = `vweo_futo1`,
    },
    vweo_gauntlet1 = {
        name = "Gauntlet S/C",
        brand = "Bravado",
        price = 78237,
        model = "vweo_gauntlet1",
        category = "muscle",
        type = 'automobile',
        hash = `vweo_gauntlet1`,
    },
    vweo_hellhound1 = {
        name = "Hellhound",
        brand = "Bravado",
        price = 85994,
        model = "vweo_hellhound1",
        category = "muscle",
        type = 'automobile',
        hash = `vweo_hellhound1`,
    },
    vweo_hpr1 = {
        name = "HPR-1 Hyperion",
        brand = "Entara",
        price = 94851,
        model = "vweo_hpr1",
        category = "super",
        type = 'automobile',
        hash = `vweo_hpr1`,
    },
    vweo_infernus1 = {
        name = "Infernus",
        brand = "Pegassi",
        price = 99059,
        model = "vweo_infernus1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vweo_infernus1`,
    },
    vweo_ingot1 = {
        name = "Ingot",
        brand = "Vulcar",
        price = 78194,
        model = "vweo_ingot1",
        category = "super",
        type = 'automobile',
        hash = `vweo_ingot1`,
    },
    vweo_jv901 = {
        name = "JV90",
        brand = "Entara",
        price = 86317,
        model = "vweo_jv901",
        category = "super",
        type = 'automobile',
        hash = `vweo_jv901`,
    },
    vweo_spritzer1 = {
        name = "Spritzer",
        brand = "Benefactor",
        price = 80346,
        model = "vweo_spritzer1",
        category = "super",
        type = 'automobile',
        hash = `vweo_spritzer1`,
    },
    vweo_kuruma1 = {
        name = "Kuruma",
        brand = "Karin",
        price = 87008,
        model = "vweo_kuruma1",
        category = "super",
        type = 'automobile',
        hash = `vweo_kuruma1`,
    },
    vweo_majimalm1 = {
        name = "Maji Malm",
        brand = "Annis",
        price = 74651,
        model = "vweo_majimalm1",
        category = "super",
        type = 'automobile',
        hash = `vweo_majimalm1`,
    },
    vweo_monster1 = {
        name = "Monster (Limo)",
        brand = "Albany",
        price = 57276,
        model = "vweo_monster1",
        category = "offroad",
        type = 'automobile',
        hash = `vweo_monster1`,
    },
    vweo_r70k1 = {
        name = "R70000",
        brand = "Karin",
        price = 81861,
        model = "vweo_r70k1",
        category = "super",
        type = 'automobile',
        hash = `vweo_r70k1`,
    },
    vweo_requiem1 = {
        name = "Requiem",
        brand = "Annis",
        price = 80698,
        model = "vweo_requiem1",
        category = "coupes",
        type = 'automobile',
        hash = `vweo_requiem1`,
    },
    vweo_sabregt1 = {
        name = "Sabre GT",
        brand = "Declasse",
        price = 83744,
        model = "vweo_sabregt1",
        category = "muscle",
        type = 'automobile',
        hash = `vweo_sabregt1`,
    },
    vweo_sentinel2 = {
        name = "Sentinel",
        brand = "Ubermacht",
        price = 71914,
        model = "vweo_sentinel2",
        category = "super",
        type = 'automobile',
        hash = `vweo_sentinel2`,
    },
    vweo_torero1 = {
        name = "Torero",
        brand = "Pegassi",
        price = 78810,
        model = "vweo_torero1",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vweo_torero1`,
    },
    vweo_zion1 = {
        name = "Zion",
        brand = "Ubermacht",
        price = 72551,
        model = "vweo_zion1",
        category = "super",
        type = 'automobile',
        hash = `vweo_zion1`,
    },
    vweo_zion2 = {
        name = "Zion",
        brand = "Ubermacht",
        price = 77766,
        model = "vweo_zion2",
        category = "sportsclassics",
        type = 'automobile',
        hash = `vweo_zion2`,
    },
    vweo_zr3501 = {
        name = "ZR350",
        brand = "Annis",
        price = 91328,
        model = "vweo_zr3501",
        category = "super",
        type = 'automobile',
        hash = `vweo_zr3501`,
    },
}